on:
  push:
    branches:
      - master

name: Demonstration search

jobs:
  search:
    name: Publish demonstration search
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          branch: gh-pages
          folder: html
